# Copyright 2025 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Test setting new line-breakpoint after re-running with removed
# breakpoint inside solib.

require !use_gdb_stub
require allow_shlib_tests

standard_testfile so-impl-ld.c
set libfile "solib1"
set libsrc  $srcdir/$subdir/$libfile.c
set lib_sl  [standard_output_file $libfile.sl]

set lib_opts  {debug shlib}
set exec_opts [list debug shlib=$lib_sl]

if { [build_executable "build shlib" $lib_sl $libsrc $lib_opts] != 0 } {
    return
}

if { [prepare_for_testing "prepare" $testfile $srcfile $exec_opts] != 0 } {
    return
}

gdb_breakpoint solib_main

gdb_test "run" "Breakpoint $decimal, solib_main.*" "run with breakpoint"

delete_breakpoints

gdb_test "with confirm off -- run" \
    "\[Inferior $decimal \\(\[^\r\n\]*\\) exited normally\]" \
    "run without breakpoint"

set bp_location [gdb_get_line_number "result = solib_main"]
# This breakpoint caused a use-after-free crash with ASan, because
# the last displayed sal contained a reference to a symtab that was
# already freed in the previous run.
gdb_test "break $bp_location" "Breakpoint $decimal at .*"
